site_name: EasyVirtualMotionCaptureForUnity-documents
site_url: https://gpsnmeajp.github.io/EasyVirtualMotionCaptureForUnity-documents/
theme:
  name: material
  language: ja
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate 
    - navigation.top
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: green
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
        
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
  - pymdownx.tilde:

extra_css:
  - stylesheets/extra.css
